### ISSUE TITLE
Controller Helpers not working

### ISSUE THREAD

**Issue by conacelelena** [daddyz/evercookie#10]
I tried using evercookie_is_set?(:key) inside a method in my controller and it raise an error saying the function is not known.
Am I doing something wrong?

Elena

**Comment by daddyz** [comment]
Hi, did you put `include Evercookie::ControllerHelpers` in your controller?
If so and it still doesn't work, please provide Rails and Evercookie version you are using.

**Comment by conacelelena** [comment]
It works if I include the helpers inside the controller. Thank you!
